#!/bin/sh
# Required for the OCI Provider
export TF_VAR_tenancy_ocid="ocid1.tenancy.oc1..aaaaaaaazo7h6yqgac7aunojr2tjsxux3ipdyamc3fgkvz7lubvdtsjyf4gq"
export TF_VAR_compartment_ocid="ocid1.compartment.oc1..aaaaaaaaqfrh6ndx3miiikntt4ih5v252c5l3o24qbj7mjsaqcoilwss52oq"
export TF_VAR_region="us-ashburn-1"
export TF_VAR_home_region="us-phoenix-1"
export TF_VAR_bds_instance_cluster_admin_password="V2VsY29tZTE="
export TF_VAR_ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpUa4zUZKyU3AkW9yoJTBDO550wpWZOXdHswfRq75gbJ2ZYlMtifvwiO3qUL/RIZSC6e1wA5OL2LQ97UaHrLLPXgjvKGVIDRHqPkzTOayjJ4ZA7NPNhcu6f/OxhKkCYF3TAQObhMJmUSMrWSUeufaRIujDz1HHqazxOgFk09fj4i2dcGnfPcm32t8a9MzlsHSmgexYCUwxGisuuWTsnMgxbqsj6DaY51l+SEPi5tf10iFmUWqziF0eKDDQ/jHkwLJ8wgBJef9FSOmwJReHcBY+NviwFTatGj7Cwtnks6CVomsFD+rAMJ9uzM8SCv5agYunx07hnEXbR9r/TXqgXGfN"
